version: "3.9"
services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/static_html:/usr/share/nginx/html
    depends_on:
      - flask

  flask:
    build: pythonbase
    command: gunicorn example.flask:app -b 0.0.0.0:5000
    stop_signal: SIGINT
    env_file:
      - redis-conf.env
    volumes:
      - ./code:/app
    depends_on:
      - redis

  worker:
    build: pythonbase
    command: celery --app example.celery worker --loglevel=info
    scale: 3
    volumes:
      - ./code:/app
    env_file:
      - redis-conf.env
    depends_on:
      - flask
      - redis

  redis:
    image: redis:6-alpine
